language: generic

sudo: required
services:
  - docker

before _install:
  - docker build -t vpanki/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vpanki/react-test npm test

after_success:
  - dcoker build -t vpanki/multi-client ./client
  - dcoker build -t vpanki/multi-nginx ./nginx
  - dcoker build -t vpanki/multi-server ./server
  - dcoker build -t vpanki/multi-worker ./worker

# Log in Docker CLI #
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push images #
- docker push vpanki/multi-client
- docker push vpanki/multi-nginx
- docker push vpanki/multi-server
- docker push vpanki/multi-worker
